import pymysql
db = pymysql.connect(host='switchyard.proxy.rlwy.net', user='root', password='PQmFmeJKciVtHrHhKSVveuvFbcaFGnUU', database='railway', port=57522)
cur = db.cursor()
cur.execute("""CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL, email VARCHAR(120) NOT NULL UNIQUE, phone VARCHAR(20), address TEXT, role ENUM('donor','ngo','admin') NOT NULL DEFAULT 'donor', password VARCHAR(255) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)""")
cur.execute("""CREATE TABLE IF NOT EXISTS medicines (id INT AUTO_INCREMENT PRIMARY KEY, donor_id INT NOT NULL, name VARCHAR(200) NOT NULL, quantity VARCHAR(100) NOT NULL, expiry_date DATE NOT NULL, description TEXT, photo VARCHAR(255), status ENUM('pending','approved','rejected') DEFAULT 'pending', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (donor_id) REFERENCES users(id))""")
cur.execute("""CREATE TABLE IF NOT EXISTS requests (id INT AUTO_INCREMENT PRIMARY KEY, ngo_id INT NOT NULL, medicine_id INT NOT NULL, note TEXT, status ENUM('pending','approved','in_transit','delivered') DEFAULT 'pending', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (ngo_id) REFERENCES users(id), FOREIGN KEY (medicine_id) REFERENCES medicines(id))""")
cur.execute("""INSERT IGNORE INTO users (name,email,phone,address,role,password) VALUES ('Admin','admin@medishare.com','9999999999','MediShare HQ','admin','pbkdf2:sha256:260000\\')""")
db.commit()
db.close()
print('All tables created successfully!')
